version: '3.8'

services:
  telebot:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: telegram-assistant-bot
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./.gcp-saved-tokens.json:/app/.gcp-saved-tokens.json
      - ./gcp-oauth.keys.json:/app/gcp-oauth.keys.json
